name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14
    - name: Publish if version has been updated
      run: |
        echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' > ~/.npmrc
        npm publish
      # uses: JS-DevTools/npm-publish@v1
      # with:
      #   token: ${{ secrets.GITHUB_TOKEN }}
      #   registry: https://npm.pkg.github.com/
